# Generated by Django 3.1.1 on 2021-03-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
